# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scoring/scoring.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scoring/scoring.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15scoring/scoring.proto\x12\x07scoring\"q\n\x10MpesaTransaction\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x14\n\x0c\x63ounterparty\x18\x05 \x01(\t\"S\n\rPhoneMetadata\x12\x0e\n\x06msisdn\x18\x01 \x01(\t\x12\x18\n\x10\x61\x63\x63ount_age_days\x18\x02 \x01(\x05\x12\x18\n\x10network_provider\x18\x03 \x01(\t\"o\n\x0cScoreRequest\x12/\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x19.scoring.MpesaTransaction\x12.\n\x0ephone_metadata\x18\x02 \x01(\x0b\x32\x16.scoring.PhoneMetadata\"F\n\rScoreResponse\x12\r\n\x05score\x18\x01 \x01(\x01\x12\x11\n\trisk_band\x18\x02 \x01(\t\x12\x13\n\x0b\x65xplanation\x18\x03 \x01(\t2O\n\x0eScoringService\x12=\n\x0c\x43omputeScore\x12\x15.scoring.ScoreRequest\x1a\x16.scoring.ScoreResponseB/Z-github.com/eliasndungu/finscore/proto/scoringb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scoring.scoring_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/eliasndungu/finscore/proto/scoring'
  _globals['_MPESATRANSACTION']._serialized_start=34
  _globals['_MPESATRANSACTION']._serialized_end=147
  _globals['_PHONEMETADATA']._serialized_start=149
  _globals['_PHONEMETADATA']._serialized_end=232
  _globals['_SCOREREQUEST']._serialized_start=234
  _globals['_SCOREREQUEST']._serialized_end=345
  _globals['_SCORERESPONSE']._serialized_start=347
  _globals['_SCORERESPONSE']._serialized_end=417
  _globals['_SCORINGSERVICE']._serialized_start=419
  _globals['_SCORINGSERVICE']._serialized_end=498
# @@protoc_insertion_point(module_scope)
