// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/scoring/scoring.proto

package scoring

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MpesaTransaction represents a single M-Pesa transaction record.
type MpesaTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// type is one of: SEND_MONEY, RECEIVE_MONEY, BUY_AIRTIME, PAY_BILL,
	// BUY_GOODS, WITHDRAW, DEPOSIT, FULIZA
	Type   string  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Amount float64 `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// timestamp in RFC-3339 / ISO-8601 format, e.g. "2024-01-15T10:30:00Z"
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// counterparty phone number or business short-code (may be empty)
	Counterparty  string `protobuf:"bytes,5,opt,name=counterparty,proto3" json:"counterparty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MpesaTransaction) Reset() {
	*x = MpesaTransaction{}
	mi := &file_proto_scoring_scoring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MpesaTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpesaTransaction) ProtoMessage() {}

func (x *MpesaTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoring_scoring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpesaTransaction.ProtoReflect.Descriptor instead.
func (*MpesaTransaction) Descriptor() ([]byte, []int) {
	return file_proto_scoring_scoring_proto_rawDescGZIP(), []int{0}
}

func (x *MpesaTransaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *MpesaTransaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MpesaTransaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MpesaTransaction) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *MpesaTransaction) GetCounterparty() string {
	if x != nil {
		return x.Counterparty
	}
	return ""
}

// PhoneMetadata carries subscriber-level signals.
type PhoneMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// msisdn is the Safaricom number in E.164 format, e.g. "+254712345678"
	Msisdn         string `protobuf:"bytes,1,opt,name=msisdn,proto3" json:"msisdn,omitempty"`
	AccountAgeDays int32  `protobuf:"varint,2,opt,name=account_age_days,json=accountAgeDays,proto3" json:"account_age_days,omitempty"`
	// network_provider e.g. "Safaricom", "Airtel", "Telkom"
	NetworkProvider string `protobuf:"bytes,3,opt,name=network_provider,json=networkProvider,proto3" json:"network_provider,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PhoneMetadata) Reset() {
	*x = PhoneMetadata{}
	mi := &file_proto_scoring_scoring_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneMetadata) ProtoMessage() {}

func (x *PhoneMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoring_scoring_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneMetadata.ProtoReflect.Descriptor instead.
func (*PhoneMetadata) Descriptor() ([]byte, []int) {
	return file_proto_scoring_scoring_proto_rawDescGZIP(), []int{1}
}

func (x *PhoneMetadata) GetMsisdn() string {
	if x != nil {
		return x.Msisdn
	}
	return ""
}

func (x *PhoneMetadata) GetAccountAgeDays() int32 {
	if x != nil {
		return x.AccountAgeDays
	}
	return 0
}

func (x *PhoneMetadata) GetNetworkProvider() string {
	if x != nil {
		return x.NetworkProvider
	}
	return ""
}

// ScoreRequest is the payload sent by the Go API to the Python scorer.
type ScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*MpesaTransaction    `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	PhoneMetadata *PhoneMetadata         `protobuf:"bytes,2,opt,name=phone_metadata,json=phoneMetadata,proto3" json:"phone_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreRequest) Reset() {
	*x = ScoreRequest{}
	mi := &file_proto_scoring_scoring_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreRequest) ProtoMessage() {}

func (x *ScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoring_scoring_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreRequest.ProtoReflect.Descriptor instead.
func (*ScoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_scoring_scoring_proto_rawDescGZIP(), []int{2}
}

func (x *ScoreRequest) GetTransactions() []*MpesaTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ScoreRequest) GetPhoneMetadata() *PhoneMetadata {
	if x != nil {
		return x.PhoneMetadata
	}
	return nil
}

// ScoreResponse is returned by the Python scorer to the Go API.
type ScoreResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// score is a probability in [0, 1] where higher = more creditworthy.
	Score float64 `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	// risk_band is one of: LOW, MEDIUM, HIGH, VERY_HIGH
	RiskBand string `protobuf:"bytes,2,opt,name=risk_band,json=riskBand,proto3" json:"risk_band,omitempty"`
	// explanation is a human-readable summary of the key scoring factors.
	Explanation   string `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreResponse) Reset() {
	*x = ScoreResponse{}
	mi := &file_proto_scoring_scoring_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreResponse) ProtoMessage() {}

func (x *ScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoring_scoring_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreResponse.ProtoReflect.Descriptor instead.
func (*ScoreResponse) Descriptor() ([]byte, []int) {
	return file_proto_scoring_scoring_proto_rawDescGZIP(), []int{3}
}

func (x *ScoreResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoreResponse) GetRiskBand() string {
	if x != nil {
		return x.RiskBand
	}
	return ""
}

func (x *ScoreResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

var File_proto_scoring_scoring_proto protoreflect.FileDescriptor

const file_proto_scoring_scoring_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/scoring/scoring.proto\x12\ascoring\"\xa7\x01\n" +
	"\x10MpesaTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\"\n" +
	"\fcounterparty\x18\x05 \x01(\tR\fcounterparty\"|\n" +
	"\rPhoneMetadata\x12\x16\n" +
	"\x06msisdn\x18\x01 \x01(\tR\x06msisdn\x12(\n" +
	"\x10account_age_days\x18\x02 \x01(\x05R\x0eaccountAgeDays\x12)\n" +
	"\x10network_provider\x18\x03 \x01(\tR\x0fnetworkProvider\"\x8c\x01\n" +
	"\fScoreRequest\x12=\n" +
	"\ftransactions\x18\x01 \x03(\v2\x19.scoring.MpesaTransactionR\ftransactions\x12=\n" +
	"\x0ephone_metadata\x18\x02 \x01(\v2\x16.scoring.PhoneMetadataR\rphoneMetadata\"d\n" +
	"\rScoreResponse\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x01R\x05score\x12\x1b\n" +
	"\trisk_band\x18\x02 \x01(\tR\briskBand\x12 \n" +
	"\vexplanation\x18\x03 \x01(\tR\vexplanation2O\n" +
	"\x0eScoringService\x12=\n" +
	"\fComputeScore\x12\x15.scoring.ScoreRequest\x1a\x16.scoring.ScoreResponseB/Z-github.com/eliasndungu/finscore/proto/scoringb\x06proto3"

var (
	file_proto_scoring_scoring_proto_rawDescOnce sync.Once
	file_proto_scoring_scoring_proto_rawDescData []byte
)

func file_proto_scoring_scoring_proto_rawDescGZIP() []byte {
	file_proto_scoring_scoring_proto_rawDescOnce.Do(func() {
		file_proto_scoring_scoring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scoring_scoring_proto_rawDesc), len(file_proto_scoring_scoring_proto_rawDesc)))
	})
	return file_proto_scoring_scoring_proto_rawDescData
}

var file_proto_scoring_scoring_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_scoring_scoring_proto_goTypes = []any{
	(*MpesaTransaction)(nil), // 0: scoring.MpesaTransaction
	(*PhoneMetadata)(nil),    // 1: scoring.PhoneMetadata
	(*ScoreRequest)(nil),     // 2: scoring.ScoreRequest
	(*ScoreResponse)(nil),    // 3: scoring.ScoreResponse
}
var file_proto_scoring_scoring_proto_depIdxs = []int32{
	0, // 0: scoring.ScoreRequest.transactions:type_name -> scoring.MpesaTransaction
	1, // 1: scoring.ScoreRequest.phone_metadata:type_name -> scoring.PhoneMetadata
	2, // 2: scoring.ScoringService.ComputeScore:input_type -> scoring.ScoreRequest
	3, // 3: scoring.ScoringService.ComputeScore:output_type -> scoring.ScoreResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_scoring_scoring_proto_init() }
func file_proto_scoring_scoring_proto_init() {
	if File_proto_scoring_scoring_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scoring_scoring_proto_rawDesc), len(file_proto_scoring_scoring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scoring_scoring_proto_goTypes,
		DependencyIndexes: file_proto_scoring_scoring_proto_depIdxs,
		MessageInfos:      file_proto_scoring_scoring_proto_msgTypes,
	}.Build()
	File_proto_scoring_scoring_proto = out.File
	file_proto_scoring_scoring_proto_goTypes = nil
	file_proto_scoring_scoring_proto_depIdxs = nil
}
